title: Shafi Imran
logo: /assets/img/profile-circle.png
description: I’m an aspiring Data Analyst with a passion for turning numbers into insights. As a Business and Technology undergrad, I have knowledge from both business & tech world. Hence I’ve found my true interest in data and analytics, where I enjoy solving problems and uncovering trends. Currently learning Data Science & ML. Which will not only help me to analyze data but also identify hidden patterns and future trends within data
show_downloads: true
theme: jekyll-theme-minimal
